<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">User Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminUser') ?>">User</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <?php if(isset($fields['left'])): ?>
                                <div class="col-md-4">
                                    <?php foreach($fields['left'] as $fname): ?>
                                        <?= $form->field($fname); ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                            <?php if(isset($fields['center'])): ?>
                                <div class="col-md-4">
                                    <?php foreach($fields['center'] as $fname): ?>
                                        <?= $form->field($fname); ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                            <?php if(isset($fields['right'])): ?>
                                <div class="col-md-4">
                                    <?php foreach($fields['right'] as $fname): ?>
                                        <?= $form->field($fname); ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>