<form method="POST" class="row mb-3 needs-validation main" novalidate>
    <?= $form->csrfField('noob') ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <?= $_meta['subtitle'] ?>
                <div class="float-right">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
            <div class="card-body">
                <?php if($saved): ?>
                    <div class="alert alert-success" role="alert">
                        User profile successfully updated.
                    </div>
                <?php endif; ?>
                
                <div class="row">
                    <div class="col-md-4">
                        <?php if(isset($fields['top-left'])): ?>
                            <?php foreach($fields['top-left'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-4">
                        <?php if(isset($fields['top-center'])): ?>
                            <?php foreach($fields['top-center'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-4">
                        <?php if(isset($fields['top-right'])): ?>
                            <?php foreach($fields['top-right'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php if(isset($fields['middle'])): ?>
                            <?php foreach($fields['middle'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <?php if(isset($fields['bottom-left'])): ?>
                            <?php foreach($fields['bottom-left'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-7">
                        <?php if(isset($fields['bottom-right'])): ?>
                            <?php foreach($fields['bottom-right'] as $fname): ?>
                                <?= $form->field($fname, ($opts[$fname]??null)); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>