<form method="POST" class="row mb-3 needs-validation main" novalidate>
    <?= $form->csrfField('noob') ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Password
                <div class="float-right">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
            <div class="card-body">
                <?php if($saved): ?>
                    <div class="alert alert-success" role="alert">
                        User password successfully updated.
                    </div>
                <?php endif; ?>
                
                <div class="row">
                    <div class="col-md-4">
                        <?= $form->field('password'); ?>
                        <?= $form->field('retype-password'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>